name: beta_cinema
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  google_fonts: ^6.2.1
  font_awesome_flutter: ^10.8.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/banner1.jpg
    - assets/banner2.jpg
    - assets/banner3.png
    - assets/banner4.jpg
    - assets/mv1.jpg
    - assets/mv2.jpg
